export const EDITPUB='home/my/editPub'
export const EDITFINISH='home/my/editFinish'
export const CHANGEPUB='home/my/changePub'
export const ADDPUB='home/my/addPub'
export const DELETEPUB='home/my/deletePub'
export const SHOWDELETE='home/my/showDelete'
export const HIDEDELETE='home/my/hideDelete'